import { subDays } from "date-fns";
import type { IRoom } from "./interfaces";

const randomDate = () => {
  const daysAgo = Math.floor(Math.random() * 90);
  return subDays(new Date(), daysAgo).toUTCString();
};


export const RandomTopics = [
  "What’s the last thing that made you laugh hard?",
  "If you could instantly learn one skill, what would it be?",
  "Coffee or tea — and don’t say both",
  "What’s a movie you can rewatch anytime?",
  "Morning person or night owl?",
  "What’s a small thing that annoys you way more than it should?",
  "Do you prefer working alone or with people?",
  "What’s the best meal you’ve ever had?",
  "Beach or mountains?",
  "What’s your go-to comfort food?",

  "If you had a free plane ticket, where would you go?",
  "What’s a hobby you wish you were good at?",
  "What app do you open the most every day?",
  "What’s a song you never skip?",
  "Do you like routines or chaos?",
  "What’s something you recently learned?",
  "What’s your favorite time of day?",
  "Are you more logical or emotional?",
  "What’s a random fact you know?",
  "What’s something you’re procrastinating right now?",

  "Do you prefer texting or calling?",
  "What’s your favorite season?",
  "What’s a habit you’re trying to build?",
  "What’s a habit you’re trying to quit?",
  "What’s your favorite childhood memory?",
  "Do you believe in luck?",
  "What’s the best advice you’ve ever received?",
  "What’s a bad habit you secretly enjoy?",
  "What’s something you’re proud of?",
  "What’s your favorite way to relax?",

  "What’s the last series you watched?",
  "If you could live in any country, where?",
  "Do you like planning or going with the flow?",
  "What’s a food you’ll never understand the hype around?",
  "What’s your favorite weekend activity?",
  "What’s something everyone should try once?",
  "What’s your favorite smell?",
  "Do you like surprises?",
  "What’s a skill that’s underrated?",
  "What’s your favorite type of weather?",

  "What’s a quote you like (or hate)?",
  "What motivates you when you’re stuck?",
  "What’s your favorite simple pleasure?",
  "What’s something you miss from the past?",
  "What’s something you’re curious about lately?",
  "What’s your favorite place to think?",
  "Do you prefer books or movies?",
  "What’s a talent you admire in others?",
  "What’s your favorite way to waste time?",
  "What’s something you want to improve this year?",

  "If today was completely free, what would you do?",
  "What’s a rule you think is pointless?",
  "What’s your favorite random YouTube content?",
  "What’s something you wish people understood better?",
  "What’s your favorite late-night thought?",
  "What’s a small win from recently?",
  "Do you prefer city life or quiet places?",
  "What’s a topic you can talk about for hours?",
  "What’s your favorite kind of conversation?",
  "What makes a conversation interesting to you?",

  "What’s something that instantly improves your mood?",
  "What’s a fear you’ve overcome?",
  "What’s something you’re looking forward to?",
  "What’s your favorite sound?",
  "What’s a decision that changed your life?",
  "What’s something you want to learn next?",
  "What’s your ideal day look like?",
  "What’s a random memory that pops up often?",
  "What’s something you’ll always make time for?",
  "What’s a question you like being asked?",
];

export const rooms: (IRoom)[] = [
  {
    id: "room-1",
    topic: "Frontend Dev Chat",
    maxParticipants: 2,
    languages: ["en", "az"],
    ownerId: "user-1",
    owner: { id: "user-1", fullName: "Alice Johnson" },
    users: [
      { id: "user-1", fullName: "Alice Johnson" },
      { id: "user-2", fullName: "Bob Smith" },
      { id: "user-3", fullName: "Bob Smith" },
      { id: "user-4", fullName: "Bob Smith" },
      { id: "user-5", fullName: "Bob Smith" },
      { id: "user-6", fullName: "Bob Smith" },
      { id: "user-7", fullName: "Bob Smith" },
      { id: "user-8", fullName: "Bob Smith" },
      { id: "user-9", fullName: "Bob Smith" },
    ],
    createdAt: randomDate(),
  },
  {
    id: "room-2",
    topic: "Backend API Discussion",
    ownerId: "user-3",
    maxParticipants: 2,
    languages: ["en"],
    owner: { id: "user-3", fullName: "Charlie Brown" },
    users: [
      { id: "user-3", fullName: "Charlie Brown" },
      { id: "user-4", fullName: "Diana Prince" },
      { id: "user-5", fullName: "Evan Lee" },
    ],
    createdAt: randomDate(),
  },
  {
    id: "room-3",
    topic: "Music Production Tips",
    ownerId: "user-3",
    maxParticipants: 2,
    languages: ["az"],
    owner: { id: "user-6", fullName: "Fiona Apple" },
    users: [
      { id: "user-6", fullName: "Fiona Apple" },
      { id: "user-7", fullName: "George Harrison" },
    ],
    createdAt: randomDate(),
  },
  {
    id: "room-4",
    topic: "JavaScript Frameworks",
    ownerId: "user-3",
    maxParticipants: 2,
    languages: ["en"],

    owner: { id: "user-8", fullName: "Hannah Scott" },
    users: [
      { id: "user-8", fullName: "Hannah Scott" },
      { id: "user-9", fullName: "Ian Curtis" },
    ],
    createdAt: randomDate(),
  },
  {
    id: "room-5",
    topic: "Guitar Chords and Lessons",
    ownerId: "user-3",
    maxParticipants: 2,
    languages: ["az"],
    owner: { id: "user-10", fullName: "Jack White" },
    users: [
      { id: "user-10", fullName: "Jack White" },
      { id: "user-11", fullName: "Kurt Cobain" },
    ],
    createdAt: randomDate(),
  },
  {
    id: "room-6",
    topic: "AI and Machine Learning",
    languages: ["en"],
    ownerId: "user-3",
    maxParticipants: 2,
    owner: { id: "user-12", fullName: "Laura Palmer" },
    users: [
      { id: "user-12", fullName: "Laura Palmer" },
      { id: "user-13", fullName: "Michael Scott" },
      { id: "user-14", fullName: "Nancy Drew" },
    ],
    createdAt: randomDate(),
  },
  {
    id: "room-7",
    topic: "Electronic Music Production",
    languages: ["az"],
    ownerId: "user-3",
    maxParticipants: 2,
    owner: { id: "user-15", fullName: "Olivia Rodrigo" },
    users: [
      { id: "user-15", fullName: "Olivia Rodrigo" },
      { id: "user-16", fullName: "Paul McCartney" },
    ],
    createdAt: randomDate(),
  },
  {
    id: "room-8",
    topic: "Cloud Computing Chat",
    languages: ["en"],
    ownerId: "user-3",
    maxParticipants: 2,
    owner: { id: "user-17", fullName: "Quentin Tarantino" },
    users: [
      { id: "user-17", fullName: "Quentin Tarantino" },
      { id: "user-18", fullName: "Rachel Green" },
    ],
    createdAt: randomDate(),
  },
  {
    id: "room-9",
    topic: "Songwriting Techniques",

    languages: ["az"],
    ownerId: "user-3",
    maxParticipants: 2,
    owner: { id: "user-19", fullName: "Sam Smith" },
    users: [
      { id: "user-19", fullName: "Sam Smith" },
      { id: "user-20", fullName: "Taylor Swift" },
    ],
    createdAt: randomDate(),
  },
  {
    id: "room-10",
    topic: "DevOps & CI/CD",

    languages: ["en"],
    ownerId: "user-3",
    maxParticipants: 2,
    owner: { id: "user-21", fullName: "Uma Thurman" },
    users: [
      { id: "user-21", fullName: "Uma Thurman" },
      { id: "user-22", fullName: "Victor Stone" },
    ],
    createdAt: randomDate(),
  },
  {
    id: "room-11",
    topic: "Piano Covers & Tutorials",

    languages: ["az"],
    ownerId: "user-3",
    maxParticipants: 2,
    owner: { id: "user-23", fullName: "Will Smith" },
    users: [
      { id: "user-23", fullName: "Will Smith" },
      { id: "user-24", fullName: "Xavier Woods" },
    ],
    createdAt: randomDate(),
  },
  {
    id: "room-12",
    topic: "Cybersecurity Chat",

    languages: ["en"],
    ownerId: "user-3",
    maxParticipants: 2,
    owner: { id: "user-25", fullName: "Yara Shahidi" },
    users: [
      { id: "user-25", fullName: "Yara Shahidi" },
      { id: "user-26", fullName: "Zachary Levi" },
    ],
    createdAt: randomDate(),
  },
  {
    id: "room-13",
    topic: "Hip Hop Production",

    languages: ["az"],
    ownerId: "user-3",
    maxParticipants: 2,
    owner: { id: "user-27", fullName: "Adele Laurie" },
    users: [
      { id: "user-27", fullName: "Adele Laurie" },
      { id: "user-28", fullName: "Bruno Mars" },
    ],
    createdAt: randomDate(),
  },
  {
    id: "room-14",
    topic: "React Native Developers",

    languages: ["en"],
    ownerId: "user-3",
    maxParticipants: 2,
    owner: { id: "user-29", fullName: "Chris Evans" },
    users: [
      { id: "user-29", fullName: "Chris Evans" },
      { id: "user-30", fullName: "Daisy Ridley" },
    ],
    createdAt: randomDate(),
  },
  {
    id: "room-15",
    topic: "Indie Music Hangout",

    languages: ["az"],
    ownerId: "user-3",
    maxParticipants: 2,
    owner: { id: "user-31", fullName: "Eminem" },
    users: [
      { id: "user-31", fullName: "Eminem" },
      { id: "user-32", fullName: "Freddie Mercury" },
    ],
    createdAt: randomDate(),
  },
];
