

export const RandomTopics = [
  "What’s the last thing that made you laugh hard?",
  "If you could instantly learn one skill, what would it be?",
  "Coffee or tea — and don’t say both",
  "What’s a movie you can rewatch anytime?",
  "Morning person or night owl?",
  "What’s a small thing that annoys you way more than it should?",
  "Do you prefer working alone or with people?",
  "What’s the best meal you’ve ever had?",
  "Beach or mountains?",
  "What’s your go-to comfort food?",

  "If you had a free plane ticket, where would you go?",
  "What’s a hobby you wish you were good at?",
  "What app do you open the most every day?",
  "What’s a song you never skip?",
  "Do you like routines or chaos?",
  "What’s something you recently learned?",
  "What’s your favorite time of day?",
  "Are you more logical or emotional?",
  "What’s a random fact you know?",
  "What’s something you’re procrastinating right now?",

  "Do you prefer texting or calling?",
  "What’s your favorite season?",
  "What’s a habit you’re trying to build?",
  "What’s a habit you’re trying to quit?",
  "What’s your favorite childhood memory?",
  "Do you believe in luck?",
  "What’s the best advice you’ve ever received?",
  "What’s a bad habit you secretly enjoy?",
  "What’s something you’re proud of?",
  "What’s your favorite way to relax?",

  "What’s the last series you watched?",
  "If you could live in any country, where?",
  "Do you like planning or going with the flow?",
  "What’s a food you’ll never understand the hype around?",
  "What’s your favorite weekend activity?",
  "What’s something everyone should try once?",
  "What’s your favorite smell?",
  "Do you like surprises?",
  "What’s a skill that’s underrated?",
  "What’s your favorite type of weather?",

  "What’s a quote you like (or hate)?",
  "What motivates you when you’re stuck?",
  "What’s your favorite simple pleasure?",
  "What’s something you miss from the past?",
  "What’s something you’re curious about lately?",
  "What’s your favorite place to think?",
  "Do you prefer books or movies?",
  "What’s a talent you admire in others?",
  "What’s your favorite way to waste time?",
  "What’s something you want to improve this year?",

  "If today was completely free, what would you do?",
  "What’s a rule you think is pointless?",
  "What’s your favorite random YouTube content?",
  "What’s something you wish people understood better?",
  "What’s your favorite late-night thought?",
  "What’s a small win from recently?",
  "Do you prefer city life or quiet places?",
  "What’s a topic you can talk about for hours?",
  "What’s your favorite kind of conversation?",
  "What makes a conversation interesting to you?",

  "What’s something that instantly improves your mood?",
  "What’s a fear you’ve overcome?",
  "What’s something you’re looking forward to?",
  "What’s your favorite sound?",
  "What’s a decision that changed your life?",
  "What’s something you want to learn next?",
  "What’s your ideal day look like?",
  "What’s a random memory that pops up often?",
  "What’s something you’ll always make time for?",
  "What’s a question you like being asked?",
];