export const RandomTopics = [
  "What’s the last thing that made you laugh hard?",
  "If you could instantly learn one skill, what would it be?",
  "Coffee or tea — and don’t say both",
  "What’s a movie you can rewatch anytime?",
  "Morning person or night owl?",
  "What’s a small thing that annoys you way more than it should?",
  "Do you prefer working alone or with people?",
  "What’s the best meal you’ve ever had?",
  "Beach or mountains?",
  "What’s your go-to comfort food?",

  "If you had a free plane ticket, where would you go?",
  "What’s a hobby you wish you were good at?",
  "What app do you open the most every day?",
  "What’s a song you never skip?",
  "Do you like routines or chaos?",
  "What’s something you recently learned?",
  "What’s your favorite time of day?",
  "Are you more logical or emotional?",
  "What’s a random fact you know?",
  "What’s something you’re procrastinating right now?",

  "Do you prefer texting or calling?",
  "What’s your favorite season?",
  "What’s a habit you’re trying to build?",
  "What’s a habit you’re trying to quit?",
  "What’s your favorite childhood memory?",
  "Do you believe in luck?",
  "What’s the best advice you’ve ever received?",
  "What’s a bad habit you secretly enjoy?",
  "What’s something you’re proud of?",
  "What’s your favorite way to relax?",

  "What’s the last series you watched?",
  "If you could live in any country, where?",
  "Do you like planning or going with the flow?",
  "What’s a food you’ll never understand the hype around?",
  "What’s your favorite weekend activity?",
  "What’s something everyone should try once?",
  "What’s your favorite smell?",
  "Do you like surprises?",
  "What’s a skill that’s underrated?",
  "What’s your favorite type of weather?",

  "What’s a quote you like (or hate)?",
  "What motivates you when you’re stuck?",
  "What’s your favorite simple pleasure?",
  "What’s something you miss from the past?",
  "What’s something you’re curious about lately?",
  "What’s your favorite place to think?",
  "Do you prefer books or movies?",
  "What’s a talent you admire in others?",
  "What’s your favorite way to waste time?",
  "What’s something you want to improve this year?",

  "If today was completely free, what would you do?",
  "What’s a rule you think is pointless?",
  "What’s your favorite random YouTube content?",
  "What’s something you wish people understood better?",
  "What’s your favorite late-night thought?",
  "What’s a small win from recently?",
  "Do you prefer city life or quiet places?",
  "What’s a topic you can talk about for hours?",
  "What’s your favorite kind of conversation?",
  "What makes a conversation interesting to you?",

  "What’s something that instantly improves your mood?",
  "What’s a fear you’ve overcome?",
  "What’s something you’re looking forward to?",
  "What’s your favorite sound?",
  "What’s a decision that changed your life?",
  "What’s something you want to learn next?",
  "What’s your ideal day look like?",
  "What’s a random memory that pops up often?",
  "What’s something you’ll always make time for?",
  "What’s a question you like being asked?",

  "What is your favourite thing about being alive?",
  "Dog or cat person?",
  "Is there life after death?",
  "What’s your book recommendation?",
  "What would your job be in prison?",
  "Have you ever been arrested?",
  "How much can you bench?",
  "What do you like to do?",
  "What are your biggest insecurities?",
  "Have you ever experienced a friendship break-up?",
  "What’s your favourite book?",
  "If you could wave a magic wand, what would you change about your life?",
  "How did you decide to call your child or pet the name you did? Or: how did your parents name you?",
  "Where have you enjoyed travelling or visiting?",
  "What’s your favourite Billy Joel song?",
  "What are you currently reading?",
  "Do you know where the toilets are?",
  "Anything weighing on your mind lately?",
  "Any craic?",
  "What is truth?",
  "Favourite holiday you’ve ever been on?",
  "If skill, experience or capability were no issue, what profession would you like to have?",
  "What’s the one thing in your house you don’t think anyone else has?",
  "What lunch box did you have as a kid?",
  "Have you ever farted in a lift?",
  "Rank your favourite forms of potato?",
  "Shall we not talk about the weather?",
  "If you had to be an inanimate object for a day, what would you wish to be and why?",
  "You’re preparing for Armageddon but only allowed three types of tinned food - what would you choose?",
  "If you had a soundtrack to your life, what would it be?",
  "Have you ever taken a hallucinogenic drug?",
  "What’s keeping you busy this week?",
  "What’s your favourite sandwich?",
  "How would you rate your day out of 10 so far and why?",
  "Would you like to see a picture of my dog?",
  "Fries or chips?",
  "What’s your favourite Madonna song? (You can choose one classic and one modern).",
  "Sweet or salty popcorn?",
  "Red or blue?",
  "Favourite chocolate bar or crisp?",
  "If you were a celebrity, what reality TV show would you say yes to?",
  "What is your favourite cheese?",
  "What’s your favourite condiment?",
  "What biscuit do you most identify with?",
  "When was the last time you quit?",
  "Would you prefer to have teeth for pubic hair or pubic hair for teeth?",
  "What do you like to do for fun?",
  "What’s your hot take or unpopular opinion?",
  "What are you passionate about?",
  "What did you eat for lunch today?",
  "What’s one thing that surprised you about today?",
  "What’s a totally normal thing you have never done? Mine is swim.",
  "So what don’t you do?",
  "What’s something that’s been fun for you this week?",
  "What would your death row meal be?",
  "Anchovies or oysters?",
  "If you had a secret passage, where would you want it to lead?",
  "What is your main passion in life?",
  "What blood type are you?",
  "Is a hamburger a sandwich?",
  "Do you squiggle or splodge ketchup on chips?",
  "What makes you come alive?",
  "How will AI affect your job?",
  "What are you most proud of about yourself?",
  "What would your prison strategy be?",
  "Would you rather be a duck-sized horse or a horse-sized duck?",
  "What made you smile today?",
  "What’s the best question you’ve ever been asked?",
  "Who’s the most influential person in your life?",
  "Where would you be if you hadn’t followed your dream?",
  "What’s the best decision you’ve ever made in your life?",
  "What’s your deepest regret and how can you forgive yourself or make amends?",
  "What interests you about the person sitting across from (or next to you)?",
  "If you could change one thing about the world, what would it be?",
  "If you could bestow a superpower on your child (or a loved one), what would it be?",
  "What’s your biggest pet peeve?",
  "What’s a red flag about you?",
  "What’s a green flag about you?",
  "What color are you (in mood or feeling) and why?",
  "What helps you breathe easy?",
  "What do you have faith in right now?",
  "What’s changing in your life (for the better)?",
  "Who’s the most joyful person you’ve ever met?",
  "What’s been the best moment of your life so far?",
  "Do you believe in second chances?",
  "What’s something the person across from you doesn’t know about you?",
  "If you could teleport to any location, where would it be?",
  "Are you honest?",
  "Are you going through anything the person across from you doesn’t know about?",
  "Who do you trust most in life?",
  "What’s the most important characteristic you look for in a partner?",
  "What’s most important to you right now?",
  "What question can’t you seem to find the answer to?",
  "What’s the biggest “what if” in your mind? (from ourmindfullife.com)",
  "Who’s the one who got away?",
  "What’s the first thing that comes to mind when you think of success?",
  "Past or present is there someone you wish you made amends with? If so, who and why?",
  "What’s the question you want to ask most? To whom and why?",
  "Who is someone you wish was still around?",
  "How have you shown up for yourself lately?",
  "What’s your worst tendency?",
  "What’s your best quality?",
  "What’s your superpower?",
  "What’s the superpower of the person across from you?",
  "If you could receive closure from one person, who would it be?",
  "Are you resisting change? If so, why?",
  "In your own words, what does love mean?",
  "In your own words, what does self-worth mean?",
  "Have you made space in your life for what you want?",
  "What’s a moment you will cherish forever?",
  "Do you have feelings for anyone that others don’t know about?",
  "If you could tell your childhood crush one thing, what would it be?",
  "How do you handle anger?",
  "What’s special about this moment?",
  "What’s been the miracle in the mundane for you lately?",
  "Where have you felt most rejected?",
  "Where have you felt most accepted?",
  "What have you learned about yourself in the past year?",
  "What about yourself do you have trouble acknowledging?",
  "What has been your most valuable life lesson?",
  "How do you reconnect with yourself after loss?",
  "What do you need most right now?",
  "What are you looking forward to?",
  "Who always has your best interest in mind?",
  "If you could give someone a star on the Walk Of Fame in your life, who would it be?",
  "What scares you the most?",
  "What’s the most sacred thing about you?",
  "What life lesson have you learned the hard way?",
  "What makes you stand out in the crowd?",
  "What’s something that shocked you about the person sitting next to you?",
  "What’s been your biggest challenge in life and how did you overcome it?",
  "What shocks you about yourself?",
  "Is there a dream you’re hiding from others?",
  "If you could adopt another perspective about life, what would it be?",
  "If you could ask God, Life, The Angels, or Powers That Be any question (and receive a direct answer), what would it be?",
  "What’s one thought-provoking question you would ask? Ask it.",
  "What wish came true when you met the person next to you?",
];
